# Generated by Django 5.1.4 on 2024-12-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_2fa_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='secret_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
