# Generated by Django 5.1.4 on 2024-12-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_useraccount_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
