# Generated by Django 5.1.4 on 2024-12-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen_by_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
