services:

  frontend:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./ssl:/ssl
      - ${HOME}/Desktop/42-ft_transcendence/frontend:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/django.conf
      - assetsVolume:/var/www/html/assets/avatars/
      - staticVolume:/var/www/html/static
    networks:
      - myNet
    ports: 
      - 443:443
      - 4242:4242
    restart: unless-stopped
    depends_on:
      - backend

#-------------------------------------------

  backend:
    image: backend:django
    build:
      context: .
      dockerfile: backendDockerfile
    container_name: backend
    environment:
      - PYTHONUNBUFFERED=1 # to see the asgi server's output in docker logs command
      - PIP_ROOT_USER_ACTION=ignore # for preventing warning of running pip as root
    volumes:
      - ${HOME}/Desktop/42-ft_transcendence/backend:/app
      - assetsVolume:/app/assets/avatars/
      - staticVolume:/app/assets/static/
      - backendVolume:/root/.cache/pip/
      - ./ssl:/ssl
    networks:
      - myNet
    ports:
      - 8000:8000 # for admin interface
    restart: unless-stopped
    depends_on:
      - redis
      - postgres

#-------------------------------------------

  redis:
    image: redis:bookworm
    container_name: redis
    volumes:
      - redisVolume:/data
    networks:
      - myNet
    restart: unless-stopped

#-------------------------------------------

  postgres:
    image: postgres:14.15-alpine
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=root
      # - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgresVolume:/var/lib/postgresql/data
      - ./postgres.sh:/docker-entrypoint-initdb.d/postgres.sh
    networks:
      - myNet
    restart: unless-stopped


networks:
  myNet:

volumes:
  postgresVolume:
  backendVolume:
  redisVolume:
  assetsVolume:
  staticVolume:
