services:

  frontend:
    image: frontend:nginx
    build:
      context: .
      dockerfile: frontendDockerfile
    container_name: frontend
    volumes:
      - ${HOME}/Desktop/42-ft_transcendence/frontend:/var/www/html
    ports:
      - 4242:4242
    restart: unless-stopped
    depends_on:
      - backend

#-------------------------------------------

  backend:
    image: backend:django
    build:
      context: .
      dockerfile: backendDockerfile
    container_name: backend
    environment:
      - PYTHONUNBUFFERED=1 # to see the asgi server's output in docker logs command
      - PIP_ROOT_USER_ACTION=ignore # for preventing warning of running pip as root
    volumes:
      - ${HOME}/Desktop/42-ft_transcendence/backend:/app
      - backendVolume:/root/.cache/pip/
    networks:
      - myNet
    ports:
      - 8000:8000 # for admin interface
    restart: unless-stopped
    depends_on:
      - redis
      - postgres

#-------------------------------------------

  redis:
    image: redis:bookworm
    container_name: redis
    volumes:
      - redisVolume:/data
    networks:
      - myNet
    restart: unless-stopped

#-------------------------------------------

  postgres:
    image: postgres:14.15-alpine
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=root
      # - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgresVolume:/var/lib/postgresql/data
      - ./postgres.sh:/docker-entrypoint-initdb.d/postgres.sh
    networks:
      - myNet
    restart: unless-stopped


networks:
  myNet:

volumes:
  postgresVolume:
  backendVolume:
  redisVolume: